### ISSUE TITLE
Question- Did you have to add any annotations to your nginx-ingress controller yaml?

### ISSUE THREAD

**Issue by luis-echegaray** [lenardchristopher/Identity-Server-4-and-NGINX-Ingress-in-Azure-Kubernetes#2]
Did you have to add any annotations to your Ingress controller yaml
for example, i have sites running right now like this:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: clients-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt
```
